server:
  shutdown: graceful
spring:
  profiles:
    active: development
  application:
    name: argonaut
  lifecycle:
    timeout-per-shutdown-phase: 1m
aws:
  s3:
    accessKey: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
github:
  id: ${GITHUB_ID}
  token: ${GITHUB_TOKEN}
workspace:
  path: {WORKSPACE_PATH}